version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    rebase-strategy: auto
    schedule:
      interval: weekly
    versioning-strategy: lockfile-only
    labels:
      - dependencies
    open-pull-requests-limit: 10
