name: 🐞 Report a bug
description: Something has unexpectedly gone wrong and needs to be fixed
labels:
  - bug
  - triage
body:
  - type: markdown
    attributes:
      value: |
        ##  Quick Checklist
        Thank you for taking the time to file a bug report! Please fill out this form as completely as possible.

        ✅ I am using the **latest version of oneRepo** and all plugins.
        ✅ I am using a version of Node that oneRepo supports (`>=18.14.1`)
  - type: markdown
    attributes:
      value: |
        First, to best help, it might be important to know some details about your system, as differing versions can be very impactful!
  - type: input
    id: version
    attributes:
      label: What version of oneRepo are you using?
      description: 'Run `one --version` and paste the output here.'
  - type: textarea
    id: envinfo
    attributes:
      label: Environment info
      description: Run `npx envinfo --system --binaries` and paste the output here. If this is a CI system, please enumerate information to your best guess.
      placeholder: |
        System:
          OS: macOS 13.2
          CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
          Memory: 85.71 MB / 16.00 GB
          Shell: 5.8.1 - /bin/zsh
        Binaries:
          Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
          Yarn: 3.3.1 - /usr/local/bin/yarn
          npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
      render: sh
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        Okay, let’s figure out what's going on…
  - type: input
    id: command
    attributes:
      label: Command
      description: What was the exact command that was run?
      placeholder: one tasks -c pre-commit -w tacos
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: What actually happened?
      description: Please include relevant log output. If possible, re-run with `-vvvvv` (5 `v`s) to output extra verbosity.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: checkboxes
    id: participation
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request for this issue.
