name: 💡 Feature request
description: I have a need for a new feature
labels:
  - feature
  - triage
body:
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem
      description: What is problem or issue that you’re looking to solve? What other things have you tried that did not provide the results you wanted – and why?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Suggest a solution
      description: Propose suggestions for ways that oneRepo coulid solve the problem you’ve described.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://onerepo.tools/docs/contributing/code-of-conduct/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
