[dev]
  framework = "astro"
  targetPort = 3000
  autoLaunch = false

[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../modules/ ../plugins/"

[[edge_functions]]
  path = "/*"
  function = "theme"

[[edge_functions]]
  path = "/docs/*"
  function = "theme"

[[edge_functions]]
  path = "/api/theme/*"
  function = "set-theme"
